import { BlueboxMetadataRow, BlueboxProgrammingRow } from "../../../types";

export const defaultBlueboxProgramming: BlueboxProgrammingRow = {
  "Bluebox Movie Filename": "",
  "Movie/Series Title": "",
  "Audio Dubs": {},
  "Dynamic Subs": {},
};

export const defaultBlueboxMetadata: BlueboxMetadataRow = {
  Category: "",
  "Sub-Category": "",
  Title: "",
  "Title Length Check": "",
  Genre: "",
  Rating: "",
  Runtime: "",
  "Production Year": "",
  Cast: "",
  Director: "",
  Reserved1: "",
  Reserved2: "",
  Reserved3: "",
  "Start Date": "",
  "End Date": "",
  Status: "",
  featured: "",
  "featured order": "",
  Synopsis: "",
  "Synopsis Length": "",
  "Content From": "",
  "Content Delivery Method": "",
  Reserved4: "",
  DRM: "",
  Reserved5: "",
  "Thumbnail Image Filename": "",
  "Synopsis Image Filename": "",
  Dubs: "",
  Subs: "",
  "Dynamic Subs": "",
  "Content Filename": "",
  Reserved6: "",
};
