import { ViasatHeader } from "../../../types/systems/viasat";
import { createSubfields } from "../../util";

export const viasatFilmHeader: ViasatHeader = [
  null,
  { label: "Title", value: "Title.value" },
  { label: "CC", value: "Title.CC" },
  { label: "Synopsis", value: "Synopsis.value" },
  { label: "CC", value: "Synopsis.CC" },
  null,
  "People Score",
  "Category List",
  "Genre",
  "Rating",
  "Rating Advisor",
  "Director",
  { label: "Cast", value: "Cast.value" },
  { label: "CC", value: "Cast.CC" },
  ...createSubfields(
    "Languages",
    "Lang",
    [{ csvField: "Lang", value: "value", addNumber: true }],
    6
  ),
  ...createSubfields(
    "Sub Embed",
    "Sub Embed",
    [{ csvField: "Sub Embed", value: "value", addNumber: true }],
    2
  ),
  "Closed Caps",
  ...createSubfields(
    "Sub Dynamic",
    "Sub Dynamic",
    [{ csvField: "Sub Dynamic", value: "value", addNumber: true }],
    2
  ),
  "Length",
  "Projected Size (MB)",
  "Year of Release",
  "R",
  "Status",
  "Start Date",
  "End Date",
  "TH or ED",
  "Ratio",
  "Dist",
  "Lab",
  "Pre-roll 1 (Prev Cycle Ad Pools)",
  "Pre-roll 2 (Curr Cycle Ad Pools)",
  "Pre-roll 3 (Warning Slate)",
  "Dated Version",
  "R",
  "Feature File Name (.mp4)",
  "R",
  "Poster Image File Name (.jpg)",
];

export const viasatTvHeader: ViasatHeader = [
  null,
  { label: "Title", value: "Title.value" },
  { label: "Season", value: "Title.Season" },
  { label: "Episode", value: "Title.Episode" },
  { label: "CC", value: "Title.CC" },
  { label: "Subtitle", value: "Subtitle.value" },
  { label: "CC", value: "Subtitle.CC" },
  { label: "Synopsis", value: "Synopsis.value" },
  { label: "CC", value: "Synopsis.CC" },
  { label: "Series Synopsis", value: "Series Synopsis.value" },
  { label: "CC", value: "Series Synopsis.CC" },
  "Category List",
  "Genre",
  "Rating",
  ...createSubfields(
    "Languages",
    "Lang",
    [{ csvField: "Lang", value: "value", addNumber: true }],
    2
  ),
  ...createSubfields("Sub Embed", "Sub Embed", ["Sub Embed"], 1),
  "Closed Caps",
  ...createSubfields("Sub Dynamic", "Sub Dynamic", ["Sub Embed"], 1),
  "Length",
  "Projected Size (MB)",
  "Dist",
  "Lab",
  "R",
  "Status",
  "Start Date",
  "End Date",
  "Ratio",
  "Pre-roll 1 (Prev Cycle Ad Pools)",
  "Pre-roll 2 (Curr Cycle Ad Pools)",
  "Pre-roll 3 (Warning Slate)",
  "Dated Version",
  "R",
  "Feature File Name (.mp4)",
  "R",
  "Series Image File Name (.jpg)",
  "R",
  "Episode Image File Name (.jpg)",
];
