import { GanttRow } from "../../../types";

export const defaultGanttRow: GanttRow = {
  Asset: "",
  Title: "",
  "Ep Title": "",
  Season: "",
  "Ep#": "",
  "Prod Code": "",
  "Credit Start": "",
  "Actual Runtime": "",
  Aspect: "",
  "Master Status": "",
  Version: "",
  Distributor: "",
  Lab: "",
  L1: "",
  L2: "",
  L3: "",
  L4: "",
  L5: "",
  L6: "",
  Sub1: "",
  Sub2: "",
  Sub3: "",
  Sub4: "",
  Sub5: "",
  Sub6: "",
};
