import { RaveCtrRow, RaveMediaGuiRow, RaveMediaRow } from "../../../types";

export const initialRaveCtrRow: RaveCtrRow = {
  Title: "",
  "Episode Title": "",
  "Season #": "",
  "Episode #": "",
  Priority: "",
  Applications: "",
  Genre: "",
  "Media Category": "",
  Runtime: "",
  Version: "",
  "New/HO": "",
  Start: "",
  End: "",
  Audio: {},
  "Sub BurnIn 1": "",
  "Sub BurnIn 2": "",
  Dynamic: {},
  Filename: "",
  Aspect: "",
  Resolution: "",
  Trailer: "",
  "Pre-Roll 1": "",
  "Pre-Roll 2": "",
  "Pre-Roll 3": "",
  "Post-Roll": "",
  "Seat Class": "",
  Route: "",
};

export const initialRaveMediaRow: RaveMediaRow = {
  MediaId: "",
  "Parent Title": "",
  "Exhibition Start": "",
  "Exhibition End": "",
  "Media Type": "",
  "Media Category": "",
  Thumbnall: "",
  Rating: "",
  ParentalLock: "",
  Priority: "",
  Collection: "",
  Artist: "",
  Album: "",
  "Media File": "",
  "Preview File": "",
  MF_Widescreen: "",
  "MF_MPEG Format": "",
  PF_Widescreen: "",
  "PF_MPEG Formate": "",
  RunTime: "",
  Encrypt: "",
  "Media Provider": "",
  "Encoding Lab": "",
  "Poster Art": "",
  "BurnedIn Subtitles": "",
  Genres: "",
  Themes: "",
  Routes: "",
  SeatZones: "",
  "Default Language": "",
  Subtype: "",
  Featured: "",
  PPVcontent: "",
  Images: "",
  Year: "",
  Language: "",
  "Channel Number": "",
  Season: "",
  Episode: "",
  "Box Type": "",
  ArrivalType: "",
  Tags: "",
  Rating_PEP: "",
  Apps: "",
};

export const initalRaveGuiRow: RaveMediaGuiRow = {
  "Parent Title": "",
  Title: "",
  "Episode Title": "",
  Language: "",
  Synopsis: "",
  SubtitleFilename: "",
  MKVSubtitleFilename: "",
  HLSSubtitleFilename: "",
  ClosedCaptioned: "",
  AudioStreamIndex: "",
  ArtistsCastMembers: "",
  LabelPublisher: "",
  Directors: "",
  DvsStreamIndex: "",
};
