import { ImmflyHeader } from "../../../types";

export const immflyHeader: ImmflyHeader = [
  "Languages/translations",
  "title",
  "episode_title",
  "season_number",
  "episode_number",
  "genre",
  "running_time",
  "rating",
  "age_restriction",
  "filename",
  "new/holdover",
  "start_date",
  "end_date",
  "country",
  "director_name",
  "cast",
  "synopsis",
  "title_year",
  "languages",
  "subtitles",
  "embedded_subtitles",
  "ID",
];
